version: '3.8'

services:
  share-screen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: share-screen
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8080}:8080"   # HTTP port
      - "${HTTPS_PORT:-8443}:8443"  # HTTPS port
    environment:
      - PORT=${PORT:-8080}
      - STUN_SERVER=${STUN_SERVER:-stun:stun.l.google.com:19302}
      - TOKEN_EXPIRY=${TOKEN_EXPIRY:-30m}
      - ENABLE_HTTPS=${ENABLE_HTTPS:-false}
      - TLS_CERT_FILE=${TLS_CERT_FILE:-/certs/server.crt}
      - TLS_KEY_FILE=${TLS_KEY_FILE:-/certs/server.key}
    volumes:
      - ./certs:/certs:ro  # Mount certificates directory
      - ./logs:/logs       # Mount logs directory (if needed for future logging)
    networks:
      - share-screen-network
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m

  # HTTPS-enabled service (alternative configuration)
  share-screen-https:
    extends: share-screen
    container_name: share-screen-https
    environment:
      - PORT=8443
      - STUN_SERVER=${STUN_SERVER:-stun:stun.l.google.com:19302}
      - TOKEN_EXPIRY=${TOKEN_EXPIRY:-30m}
      - ENABLE_HTTPS=true
      - TLS_CERT_FILE=/certs/server.crt
      - TLS_KEY_FILE=/certs/server.key
    profiles:
      - https
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider --no-check-certificate https://localhost:8443/ || exit 1"]

networks:
  share-screen-network:
    driver: bridge
    name: share-screen-network

volumes:
  certs:
    driver: local
  logs:
    driver: local