services:
  share-screen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: share-screen
    restart: unless-stopped
    ports:
      - "${HTTPS_PORT}:8443"
    environment:
      - PORT=${HTTPS_PORT}
      - STUN_SERVER=${STUN_SERVER}
      - TOKEN_EXPIRY=${TOKEN_EXPIRY}
      - ENABLE_HTTPS=true
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
    volumes:
      - ./certs:/home/rhyanz46/share-screen/certs:ro
      - ./logs:/logs
    networks:
      - share-screen-network
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider --no-check-certificate https://localhost:8443/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m

networks:
  share-screen-network:
    driver: bridge
    name: share-screen-network

volumes:
  certs:
    driver: local
  logs:
    driver: local